/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jhayduk' at '1/9/16 5:47 PM' with Gradle 2.6
 *
 * @author jhayduk, @date 1/9/16 5:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
